/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'expert',
    path: '/expert',
    component: 'layout.base$view.expert',
    meta: {
      title: 'expert',
      i18nKey: 'route.expert',
      icon: 'mdi:account-star',
      order: 1,
      userTypes: ['expert']
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 2,
      userTypes: ['personal', 'organization', 'expert']
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    },
    props: true
  },
  {
    name: 'organization',
    path: '/organization',
    component: 'layout.base',
    meta: {
      title: 'organization',
      i18nKey: 'route.organization',
      icon: 'mdi:office-building',
      order: 1,
      userTypes: ['organization']
    },
    children: [
      {
        name: 'organization_def',
        path: '/organization/def',
        component: 'view.organization_def',
        meta: {
          title: 'organization_def',
          i18nKey: 'route.organization_def'
        }
      }
    ]
  },
  {
    name: 'personal',
    path: '/personal',
    component: 'layout.base$view.personal',
    meta: {
      title: 'personal',
      i18nKey: 'route.personal',
      icon: 'mdi:account',
      order: 1,
      userTypes: ['personal']
    }
  }
];
